name: deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  BUILDKIT_PROGRESS: plain
  DOCKER_CLI_EXPERIMENTAL: enabled
  TARGET_IMAGE: zerosuxx/emartech-client-publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check version
        run: |
          export VERSION=$(npm view @emartech/client-publish version)
          docker manifest inspect $TARGET_IMAGE:$VERSION

      - name: Set up Docker Buildx
        if: failure()
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and deploy docker image
        if: failure()
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --target emartech \
            -t $TARGET_IMAGE:latest \
            -t $TARGET_IMAGE:$VERSION \
            .